- name: install rustup
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
  args:
    creates: "{{dotfiles_user_home | expanduser}}/.cargo/bin/rustup"

- name: install toolchain
  shell: |
    . {{dotfiles_user_home | expanduser}}/.cargo/env && rustup toolchain install stable
  args:
    creates: "{{dotfiles_user_home | expanduser}}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc"

- name: install rust requirements
  shell: |
   . {{dotfiles_user_home | expanduser}}/.cargo/env && cargo install {{ rust_packages | join(' ') }}
