# major help from https://github.com/hurricanehrndz/ansible-rustup/blob/master/tasks/gather-state.yml

- name: Check for presence of rustup executable
  stat:
    path: '{{dotfiles_user_home | expanduser}}/.cargo/bin/rustup'
  register: rustup_exe_status

- name: Get active toolchain version
  shell:
    cmd: "rustup default | grep -Po '^.*?(?=-{{ ansible_architecture }})'"
  register: rustup_default_output
  environment:
    RUSTUP_HOME: "{{dotfiles_user_home | expanduser}}/.rustup"
    CARGO_HOME: "{{dotfiles_user_home | expanduser}}/.cargo"
    PATH: "{{ ansible_env.PATH }}:{{dotfiles_user_home | expanduser}}/.cargo/bin"
  when: rustup_exe_status is succeeded
  changed_when: false
  ignore_errors: true

- name: Get currently active toolchain if installed and set
  when: rustup_default_output is defined and rustup_default_output.failed is false
  block:
    - name: Print current / active toolchain version
      ansible.builtin.debug:
        msg: "{{ rustup_default_output.stdout_lines[0] }}"

    - name: Set active_rustup_toolchain_version as fact
      ansible.builtin.set_fact:
        active_rustup_toolchain_version: '{{ rustup_default_output.stdout_lines[0] }}'

- name: install rustup
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: "{{dotfiles_user_home | expanduser}}/.cargo/bin/rustup"

- name: install toolchain
  command:
    argv:
      - rustup
      - default
      - "{{ rustup_default_version }}"
  environment:
    RUSTUP_HOME: "{{dotfiles_user_home | expanduser}}/.rustup"
    CARGO_HOME: "{{dotfiles_user_home | expanduser}}/.cargo"
    PATH: "{{ ansible_env.PATH }}:{{dotfiles_user_home | expanduser}}/.cargo/bin"
  when: active_rustup_toolchain_version is undefined or active_rustup_toolchain_version != rustup_default_version

- name: update rustup
  shell: |
    rustup update
  environment:
    RUSTUP_HOME: "{{dotfiles_user_home | expanduser}}/.rustup"
    CARGO_HOME: "{{dotfiles_user_home | expanduser}}/.cargo"
    PATH: "{{ ansible_env.PATH }}:{{dotfiles_user_home | expanduser}}/.cargo/bin"


- name: add net config
  blockinfile:
    path: "{{dotfiles_user_home | expanduser}}/.cargo/config.toml"
    block: |
      [net]
          git-fetch-with-cli = true
    state: present
    create: yes

- name: install rust requirements
  shell: |
   cargo install {{ rust_packages | join(' ') }}
  environment:
    RUSTUP_HOME: "{{dotfiles_user_home | expanduser}}/.rustup"
    CARGO_HOME: "{{dotfiles_user_home | expanduser}}/.cargo"
    PATH: "{{ ansible_env.PATH }}:{{dotfiles_user_home | expanduser}}/.cargo/bin"

