- name: install rustup
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
  args:
    creates: "{{dotfiles_user_home | expanduser}}/.cargo/bin/rustup"

- name: install toolchain linux
  shell: |
    . {{dotfiles_user_home | expanduser}}/.cargo/env && rustup toolchain install stable
  args:
    creates: "{{dotfiles_user_home | expanduser}}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc"
  when: ansible_distribution != "MacOSX"

- name: install toolchain macos
  shell: |
    . {{dotfiles_user_home | expanduser}}/.cargo/env && rustup toolchain install stable
  args:
    creates: "{{dotfiles_user_home | expanduser}}/.rustup/toolchains/stable-x86_64-apple-darwin/bin/rustc"
  when: ansible_distribution == "MacOSX"

- name: add net config
  blockinfile:
    path: "{{dotfiles_user_home | expanduser}}/.cargo/config.toml"
    block: |
      [net]
          git-fetch-with-cli = true
    state: present
    create: yes

- name: install rust requirements
  shell: |
   . {{dotfiles_user_home | expanduser}}/.cargo/env && cargo install {{ rust_packages | join(' ') }}
