- name: Clone nvm
  git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "{{ nvm_root }}"
    version: "v0.39.3"

- name: Install nvm
  shell: "{{ nvm_root }}/install.sh"
  args:
    executable: /bin/bash
    chdir: "{{ dotfiles_user_home }}"
  environment:
    PROFILE: "/dev/null"

- name: Install .nvmrc
  template:
    src: ".nvmrc.j2"
    dest: "{{ nvm_root }}/.nvmrc"
    owner: "{{ user }}"
    mode: "0644"

- name: "Load nvm env variables in {{ zsh_path_binding_path }}"
  lineinfile:
    dest: "{{ zsh_path_binding_path }}"
    regexp: '\.nvmrc$'
    line: "[ -f {{ nvm_root }}/.nvmrc ] && source {{ nvm_root }}/.nvmrc"
    state: present
    create: yes

- name: Install node {{item}}
  shell: "source {{ nvm_root }}/nvm.sh && nvm install {{item}}"
  args:
    executable: /bin/bash
    chdir: "{{ dotfiles_user_home }}"
    creates: "{{ nvm_root }}/versions/node/v{{item}}"
  loop: "{{ node_versions }}"
