# vim: set shiftwidth=2:
# vim: set tabstop=2:

options:
  - description: "Zsh configurations"
    key: zsh
    steps:
      - description: "Linking files"
        links:
          ~/.zshrc.d: assets/zsh/zshrc.d/
          ~/.zshrc: assets/zsh/zshrc
  - description: "Vim configurations"
    key: vim
    steps:
      - description: "Linking files"
        links:
          ~/.vim: assets/vim/vim
          ~/.vimrc: assets/vim/vimrc
      - description: "Installing vundle plugins vim"
        shell:
          - git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
          - vim +PluginInstall +qall 
  - description: "Tmux configurations"
    key: tmux
    steps:
      - description: "Cloning oh my tmux"
        shell:
          - git clone https://github.com/gpakosz/.tmux.git ~/.tmux
      - description: "linking files"
        shell:
          - ln -f -s ~/.tmux/.tmux.conf ~/.tmux.conf
        links:
          ~/.tmux.conf.local: assets/tmux/.tmux.conf.local

      
