options:
  - description: "pyenv"
    key: pyenv
    steps:
        - description: "Clone Pyenv directory"
          shell:
              - command: git clone https://github.com/pyenv/pyenv.git ~/.pyenv
                allow_fail: true
  - description: "fzf"
    key: fzf
    steps:
      - description: "cloning fzf"
        shell:
            - command: git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
              allow_fail: true
      - description: "Running fzf install"
        shell:
            - ~/.fzf/install --all
  - description: "NVM"
    key: nvm
    steps:
      - description: "Installing NVM from curl"
        shell:
            - curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash

  - description: "Zsh configurations"
    key: zsh
    steps:
      - description: "Linking files"
        links:
          ~/.zshrc.d: assets/zsh/zshrc.d/
          ~/.zshrc: assets/zsh/zshrc
          ~/.zprofile: assets/zsh/zprofile
  - description: "Vim configurations"
    key: vim
    steps:
      - description: "Linking files"
        links:
          ~/.vim: assets/vim/vim
          ~/.vimrc: assets/vim/vimrc
      - description: "Cloning vundle for vim"
        shell:
            - command: git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
              allow_fail: true
      - description: "Installing vim plugins"
        shell:
          - vim -c PluginInstall -c qall 
