# vim: set shiftwidth=2:
# vim: set tabstop=2:

options:
  - description: "pyenv"
    key: pyenv
    steps:
        - description: "Clone Pyenv directory"
          shell:
              - command: git clone https://github.com/pyenv/pyenv.git ~/.pyenv
                allow_fail: true
  - description: "fzf"
    key: fzf
    steps:
      - description: "cloning fzf"
        shell:
            - command: git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
              allow_fail: true
      - description: "Running fzf install"
        shell:
            - ~/.fzf/install --all
  - description: "NVM"
    key: nvm
    steps:
      - description: "Installing NVM from curl"
        shell:
            - curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash

  - description: "Zsh configurations"
    key: zsh
    steps:
      - description: "Linking files"
        links:
          ~/.zshrc.d: assets/zsh/zshrc.d/
          ~/.zshrc: assets/zsh/zshrc
          ~/.zprofile: assets/zsh/zprofile
  - description: "Vim configurations"
    key: vim
    steps:
      - description: "Linking files"
        links:
          ~/.vim: assets/vim/vim
          ~/.vimrc: assets/vim/vimrc
      - description: "Cloning vundle for vim"
        shell:
            - command: git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
              allow_fail: true
      - description: "Installing vim plugins"
        shell:
          - git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
          - vim -c PluginInstall -c qall 
  - description: "Tmux configurations"
    key: tmux
    steps:
      - description: "Cloning oh my tmux"
        shell:
          - git clone https://github.com/gpakosz/.tmux.git ~/.tmux
      - description: "linking files"
        shell:
          - ln -f -s ~/.tmux/.tmux.conf ~/.tmux.conf
        links:
          ~/.tmux.conf.local: assets/tmux/.tmux.conf.local

  - description: "Rust configs"
    key: rust
    steps:
      - description: "install rustup"
        shell:
          - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
          - eval /bin/zsh
          - rustup toolchain install stable
        
  - description: "Rust requirements"
    key: rust-cli
    steps:
      - description: "Install requirements"
        shell:
          - cat assets/rust/requirements.txt | xargs cargo install
          - eval /bin/zsh
