- name: Set up local workstation
  hosts: local
  roles:
    - role: packages
      tags: ['packages', 'zsh', 'fzf', 'docker', 'pyenv', 'nvm', 'vim', 'tmux', 'rust']
      when: ansible_distribution != "MacOSX"
    - role: zsh
      tags: ['zsh']
    - role: fzf
      tags: ['fzf']
    - role: docker
      tags: ['docker']
      when: ansible_distribution != "MacOSX"
    - role: pyenv
      tags: ['pyenv']
    - role: poetry
      tags: ['poetry']
    - role: 'nvm'
      tags: ['nvm']
    - role: 'vim'
      tags: ['vim']
    - role: 'tmux'
      tags: ['tmux']
    - role: 'rust'
      tags: ['rust']
    - role: 'go'
      tags: ['go']