#!/bin/bash

export run_as=""
if [ -x "$(command -v sudo)" ]; then
    export run_as="sudo"
fi
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

if [ $machine = Mac ]; then
  sh <(curl -L https://nixos.org/nix/install) --yes
elif [ $machine = Linux ]; then
  sh <(curl -L https://nixos.org/nix/install) --daemon --yes
fi

curl -fsSL https://get.jetify.com/devbox | bash -f
eval "$(devbox global shellenv)"

