- name: Upgrade packages
  package: upgrade=yes
  when: package_upgrade
  become: yes 
  become_user: root
  become_method: sudo

- name: Install packages
  package:
    name: "{{ packages }}"
    update_cache: yes
  become: yes  
  become_user: root
  become_method: sudo

- name: Install packages - linux only
  package:
    name: "{{ linux_only_packages }}"
    update_cache: yes
  become: yes  
  become_user: root
  become_method: sudo
  when: ansible_distribution != "MacOSX"

- name: Install packages - macos only
  package:
    name: "{{ macos_only_packages }}"
    update_cache: yes
  become: yes  
  become_user: root
  become_method: sudo
  when: ansible_distribution == "MacOSX"

- name: Remove packages
  package:
    name: "{{ remove_packages }}"
    update_cache: yes
    state: absent
  become: yes 
  become_user: root
  become_method: sudo
  when: remove_packages is defined
