#!/bin/bash

export run_as=""
if [ -x "$(command -v sudo)" ]; then
    export run_as="sudo"
fi
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac


# check if nix is already installed

if ! nix-build --version; then
  if [ $machine = Mac ]; then
    sh <(curl -L https://nixos.org/nix/install) --yes
  elif [ $machine = Linux ]; then
    if [ $(whoami) = root ]; then
      echo "script running as root!"
      sh <(curl -L https://nixos.org/nix/install) --daemon --yes
    else
      sh <(curl -L https://nixos.org/nix/install) --no-daemon --yes
    fi
  fi
  curl -fsSL https://get.jetify.com/devbox | bash -s -- -f
fi
