- name: Clone zsh plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ zsh_plugin_root }}/{{ item.name }}"
    version: "{{item.version | default('master')}}"
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"
  loop: "{{ zsh_plugins }}"

- name: Clone base16 shell
  git:
    repo: https://github.com/chriskempson/base16-shell.git
    dest: "{{ '~/.config/base16-shell' | expanduser}}"

- name: Set shell theme {{ theme }}
  shell: |
    BASE16_ROOT="{{ '~/.config/base16-shell' | expanduser}}"
    set -e
    eval "$("$BASE16_ROOT/profile_helper.sh")"
    _base16 "$BASE16_ROOT/scripts/base16-{{theme}}.sh" {{theme}}

  args:
    executable: /bin/zsh

- name: Install zsh
  package: name=zsh state=present
  become: '{{ansible_distribution != "MacOSX"}}'
  become_user: root
  become_method: sudo

- name: Symlink .zshrc
  file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: link
  loop:
    - {src: "{{ zsh_root }}/zshrc", dest: "{{ zsh_setting_path }}"}
    - {src: "{{ zsh_root }}/zshrc.d", dest: "{{zsh_directory}}"}
    - {src: "{{ zsh_root }}/zprofile", dest: "{{dotfiles_user_home}}/.zprofile"}

- name: change user shell to zsh
  become: yes
  user:
    name: "{{ user }}"
    shell: /bin/zsh
  when: ansible_distribution != 'MacOSX'

- name: "Source zsh directory in {{ zsh_setting_path }}"
  lineinfile:
    dest: "{{ zsh_setting_path }}"
    regexp: '^export ZSH_DIR'
    line: 'export ZSH_DIR="$(realpath {{zsh_directory_unexpended}})"'
    state: present
    create: yes

- name: "Load zsh plugins in {{ zsh_setting_path }}"
  lineinfile:
    insertafter: "PLUGINS go here$"
    dest: "{{ zsh_setting_path }}"
    regexp: '\/{{item[1]}}$'
    line: "[ -f $ZSH_DIR/plugins/{{ item[0].name }}/{{item[1]}} ] && source $ZSH_DIR/plugins/{{ item[0].name }}/{{item[1]}}"
    state: present
    create: yes
  with_subelements:
    - "{{zsh_plugins}}"
    - to_source
