zsh_root: "{{ dotfiles_home | expanduser }}/roles/zsh/files"
zsh_setting_path: "{{dotfiles_user_home}}/.zshrc"
zsh_directory: "{{dotfiles_user_home}}/.zshrc.d"
zsh_plugin_root: "{{ zsh_root }}/zshrc.d/plugins"
zsh_plugins:
  - repo: https://github.com/Aloxaf/fzf-tab.git
    name: fzf-tab
    to_source: 
      - fzf-tab.zsh
  - repo: https://github.com/romkatv/gitstatus.git
    name: gitstatus
    to_source: 
      - gitstatus.prompt.zsh
  - repo: https://github.com/jimhester/per-directory-history.git
    name: per-directory-history
    to_source: 
      - per-directory-history.zsh
  - repo: https://github.com/zsh-users/zsh-autosuggestions.git
    name: zsh-auto-suggestions
    to_source: 
      - zsh-autosuggestions.zsh
  - repo: https://github.com/larkery/zsh-histdb.git
    name: zsh-histdb
    version: 0b63f7c9f6748a1fa65b8d8e4508146da2c59087
    to_source: 
      - sqlite-history.zsh
      - histdb-interactive.zsh
  - repo: https://github.com/m42e/zsh-histdb-fzf.git
    name: zsh-histdb-fzf
    version: 56fe93f67edb32ae8b264c7222c62abccbb060ae
    to_source: 
      - fzf-histdb.zsh

