- name: Clone fzf
  git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "{{ fzf_path }}"
    version: master

- name: install fzf
  shell: "{{fzf_path}}/install"
  args:
    executable: /bin/bash
    chdir: "{{fzf_path}}"
    creates: "{{ fzf_path }}/bin/fzf"

- name: "load fzf env variables in {{ zsh_setting_path }}"
  lineinfile: 
    dest: "{{ zsh_setting_path }}"
    regexp: "{{item.regex}}"
    line: "{{item.text}}"
    state: present
    create: yes
  loop:
    - { 
        text: "[ -f {{ dotfiles_user_home }}/.fzf.zsh ] && source {{ dotfiles_user_home }}/.fzf.zsh", 
        regex: '\.fzf\.zsh$'
      }
    - { 
        text: 'export FZF_DEFAULT_OPTS="--multi --bind tab:down,btab:up,alt-s:toggle-down,alt-d:toggle-up --height 40% --layout=reverse --cycle --extended"', 
        regex: '^export FZF_DEFAULT_OPTS'
      }
