- name: Install gvm
  shell: "curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer | zsh"
  args:
    executable: /bin/zsh
    chdir: "{{ dotfiles_user_home }}"
    creates: "{{ gvm_root }}/scripts/gvm"
  environment:
    GVM_NO_UPDATE_PROFILE: "true"

- name: install go - mac
  when: ansible_distribution == "MacOSX"
  block:
    - name: install bootstrapping - mac
      package:
        name: go
    - name: install versions - mac
      shell: |
        . {{ gvm_root }}/scripts/gvm
        export GOROOT_BOOTSTRAP=$(brew --prefix golang)/libexec
        gvm install go{{item}}
      args:
        executable: /bin/zsh
        creates: "{{ gvm_root }}/gos/go{{item}}/bin/go"
      loop: "{{ go_versions }}"

- name: install go - linux
  when: ansible_distribution != "MacOSX"
  block:
    - name: install bootstrapping - linux
      shell: |
        . {{ gvm_root }}/scripts/gvm
        gvm install go1.4 -B # adds bootstrapping
      args:
        executable: /bin/zsh
        creates: "{{ gvm_root }}/gos/go1.4/bin/go"
    - name: install versions - linux
      shell: |
        . {{ gvm_root }}/scripts/gvm
        gvm use go1.4
        export GOROOT_BOOTSTRAP=$GOROOT
        gvm install go{{item}}
      args:
        executable: /bin/zsh
        creates: "{{ gvm_root }}/gos/go{{item}}/bin/go"
      loop: "{{ go_versions }}"

- name: use go {{go_global_version}} globally
  shell: |
    . {{ gvm_root }}/scripts/gvm
    gvm use go{{go_global_version}} --default
  args:
    executable: /bin/zsh

- name: "install package {{ item.name }}"
  shell: |
    . {{ gvm_root }}/scripts/gvm
    gvm use go{{go_global_version}}
    go install {{item.path}}@{{item.version}}
  args:
    executable: /bin/zsh
    creates: "{{ gvm_root }}/pkgsets/go{{go_global_version}}/global/bin/{{item.name}}"
  loop: "{{ go_packages }}"
