- name: Install tmux
  package: name=tmux state=present
  become: yes
  become_user: root
  become_method: sudo

- name: Cloning oh my tmux
  git:
    repo: "https://github.com/gpakosz/.tmux.git"
    dest: "{{ tmux_directory_path }}"
    version: master

- name: Symlink .tmux.local
  file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: link
  loop:
    - {src: "{{ tmux_root }}/.tmux.conf.local", dest: "{{ tmux_local_path }}"}
    - {src: "{{tmux_directory_path}}/.tmux.conf", dest: "{{ tmux_path }}"}
