require("common.plugins-setup")
require("common.core.options")
require("common.core.keymaps")
require("common.core.colorscheme")
require("common.plugins.comment")
require("common.plugins.scrollbar")
require("common.plugins.nvim-tree")
require("common.plugins.lualine")
require("common.plugins.bufferline")
require("common.plugins.telescope")
require("common.plugins.nvim-cmp")
require("common.plugins.lsp.mason")
require("common.plugins.lsp.lspsaga")
require("common.plugins.lsp.lspconfig")
require("common.plugins.lsp.null-ls")
require("common.plugins.autopairs")
require("common.plugins.treesitter")
require("common.plugins.gitsigns")
require("common.plugins.neoclip")
require("common.plugins.illuminate")
require("common.plugins.leap")

local function script_path()
  local str = debug.getinfo(1).source:sub(2)
  return str:match("(.*/)")
end

vim.cmd("source " .. script_path() .. "/setup.vim")
