- name: Add Docker repository
  block:
    - name: docker |no apt key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
    - name: Add Docker Repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
  become: yes

- name: Update apt and install docker-ce
  package: 
    name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
    update_cache: yes
    state: latest
  become: yes

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Add the to docker group 
  user:
    name: "{{ user }}"
    groups: docker 
    append: yes
