- name: Install vim
  package: name=vim state=present
  become: '{{ansible_distribution != "MacOSX"}}'
  become_user: root
  become_method: sudo

- name: Symlink .vimrc
  file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: link
  loop:
    - {src: "{{ vim_root }}/vimrc", dest: "{{ vim_path }}"}
    - {src: "{{ vim_root }}/vim", dest: "{{vim_directory_path}}"}
  
- name: "include vim directory in {{ zsh_setting_path }}"
  lineinfile: 
    dest: "{{ zsh_setting_path }}"
    regexp: '^export VIM_HOME'
    line: 'export VIM_HOME="$(realpath {{vim_directory_path}})"'
    state: present
    create: yes

- name: Clone vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ vim_directory_path }}/bundle/Vundle.vim"
    version: master

- name: install plugins
  shell: vim +PluginInstall +qall
  environment:
      VIM_HOME: "{{ vim_directory_path | expanduser }}"

- name: Install cmake
  package: name=cmake state=present
  become: '{{ansible_distribution != "MacOSX"}}'
  become_user: root
  become_method: sudo

- name: Compile you complete me
  shell: python install.py --all 
  args:
    executable: /bin/bash
    chdir: "{{ vim_root }}/vim/bundle/youcompleteme/"
    # creates: "{{ vim_root }}/vim/bundle/youcompleteme/"