- name: Add neovim Repository
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  become: yes
  when: '{{ansible_distribution != "MacOSX"}}'

- name: Install vim and neovim
  package: 
    name:
      - vim
      - '{{"neovim" if ansible_distribution != "MacOSX" else "nvim"}}'
    state: present
  become: '{{ansible_distribution != "MacOSX"}}' 
  become_user: root
  become_method: sudo

- name: Symlink .vimrc
  file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: link
  loop:
    - {src: "{{ vim_root }}/vimrc", dest: "{{ vim_path }}"}
    - {src: "{{ vim_root }}/vim", dest: "{{vim_directory_path}}"}
    - {src: "{{ vim_root }}/nvim", dest: "{{ dotfiles_user_home }}/.config/nvim"}
  
- name: "include vim directory in {{ zsh_setting_path }}"
  lineinfile: 
    dest: "{{ zsh_setting_path }}"
    regexp: '^export VIM_HOME'
    line: 'export VIM_HOME="$(realpath {{vim_directory_path}})"'
    state: present
    create: yes

- name: install {{ item.name }} plugin manager
  shell: "{{item.command}}"
  args:
    executable: /bin/bash
    creates: "{{ item.creates }}"
  loop:
    - {
        name: vim,
        command: "curl -fLo {{vim_directory_path | expanduser}}/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim",
        creates: "{{vim_directory_path | expanduser}}/autoload/plug.vim" 
      }
    - {
        name: neovim, 
        command: "sh -c 'curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'",
        creates: "{{dotfiles_user_home | expanduser}}/.local/share/nvim/site/autoload/plug.vim"
      }

- name: install plugins
  shell: "{{item}} +PlugInstall +qall"
  environment:
      VIM_HOME: "{{ vim_directory_path | expanduser }}"
  loop:
    - vim
    - nvim

